# Generated by Django 5.2.7 on 2025-11-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('address3', models.CharField(blank=True, max_length=255, null=True)),
                ('dist', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=20)),
                ('addhar_number', models.BigIntegerField(unique=True)),
                ('addhar_front', models.ImageField(upload_to='farmer/addhar/')),
                ('addhar_back', models.ImageField(upload_to='farmer/addhar/')),
                ('profile_image', models.ImageField(upload_to='farmer/profile/')),
                ('password', models.CharField(max_length=100)),
                ('agree', models.IntegerField(default=0)),
            ],
        ),
    ]
