# Generated by Django 5.2.7 on 2025-11-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
