# Generated by Django 5.2.7 on 2025-11-30 21:56

import farmer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_farmer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='addhar_back',
            field=models.ImageField(upload_to=farmer.models.upload_addhar_back),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='addhar_front',
            field=models.ImageField(upload_to=farmer.models.upload_addhar_front),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='profile_image',
            field=models.ImageField(upload_to=farmer.models.upload_profile_pic),
        ),
    ]
